verbatim:
  cabal-version: 3.4

name: audit
version: 0.0.0

dependencies:
  - base
  - containers
  - cooked-validators
  - data-default
  - optics-core
  - plutus-ledger
  - plutus-ledger-api
  - plutus-script-utils
  - plutus-tx
  - plutus-tx-plugin
  - prettyprinter
  - tasty
  - tasty-expected-failure
  - tasty-hunit
  - cerra-lending

library:
  source-dirs: src
  ghc-options:
    -Wall
    -fobject-code
    -fno-ignore-interface-pragmas
    -fno-omit-interface-pragmas
  default-extensions:
    - ImportQualifiedPost
    - NumericUnderscores
    - OverloadedStrings

executable:
  main: Main.hs
  source-dirs: exe
  dependencies: audit
  ghc-options:
    -Wall
  default-extensions:
    - ImportQualifiedPost
